spring:
  application:
    name: rbc
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8080
  servlet:
    context-path: /rbc

logging:
  config: classpath:log4j2.xml