spring:
  application:
    name: teaching-research-book

server:
  port: 8080
  servlet:
    context-path: /teaching-research-book
    tomcat:
      threads:
        max: 1000

logging:
  config: classpath:log4j2.xml